apiVersion: 1
datasources:
  - name: opentwins
    uid: opentwins-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: opentwins
      defaultBucket: default
    secureJsonData:
      token: $INFLUXDB_TOKEN
