#!/usr/bin/env bash
#
# Create deploy/compose/.env with fresh random credentials on first run.
# An existing .env is never touched: the services keep their state in Docker
# volumes, and regenerating passwords under them would lock you out.
#
set -euo pipefail

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/deploy/compose/.env"

if [ -f "$ENV_FILE" ]; then
  exit 0
fi

# `head` closing the pipe early makes `tr` die of SIGPIPE, which pipefail
# would turn into a fatal error, hence the `|| true`.
rand() {
  local s
  s="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-24}")" || true
  [ "${#s}" -eq "${1:-24}" ] || { echo "failed to generate a random value" >&2; exit 1; }
  printf '%s' "$s"
}
b64() { printf '%s' "$1" | base64 | tr -d '\n'; }

ditto_password="$(rand)"
devops_password="$(rand)"

umask 077
cat >"$ENV_FILE" <<ENV
# Generated by scripts/compose-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Never commit this file. Delete it only together with the volumes
# (make clean), otherwise the services keep the old passwords.

# --- network ---------------------------------------------------------------
# 127.0.0.1 keeps the stack private to this machine (MQTT and the extended
# API have no authentication). Set 0.0.0.0 to expose it on your LAN, and set
# OPENEGIZ_PUBLIC_HOST to the address browsers use to reach this machine.
OPENEGIZ_BIND=127.0.0.1
OPENEGIZ_PUBLIC_HOST=localhost
GRAFANA_PORT=3000
DITTO_PORT=8080
EXTENDED_API_PORT=8085
UNITY_PORT=8090
INFLUXDB_PORT=8086
MQTT_PORT=1883

# --- credentials (users: grafana admin, ditto ditto/devops, influxdb admin) -
GRAFANA_ADMIN_PASSWORD=$(rand)
DITTO_PASSWORD=${ditto_password}
DITTO_DEVOPS_PASSWORD=${devops_password}
DITTO_BASIC_AUTH=$(b64 "ditto:${ditto_password}")
DITTO_DEVOPS_BASIC_AUTH=$(b64 "devops:${devops_password}")
INFLUXDB_ADMIN_PASSWORD=$(rand)
INFLUXDB_TOKEN=$(rand 40)
ENV

echo "Created $ENV_FILE with new random credentials."
